// Version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: modules/item/itemPb/itemPb.proto

package hello_sekai_shop_tutorial

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Structures
type FindItemsInIdsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *FindItemsInIdsReq) Reset() {
	*x = FindItemsInIdsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_item_itemPb_itemPb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindItemsInIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindItemsInIdsReq) ProtoMessage() {}

func (x *FindItemsInIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_item_itemPb_itemPb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindItemsInIdsReq.ProtoReflect.Descriptor instead.
func (*FindItemsInIdsReq) Descriptor() ([]byte, []int) {
	return file_modules_item_itemPb_itemPb_proto_rawDescGZIP(), []int{0}
}

func (x *FindItemsInIdsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type FindItemsInIdsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *FindItemsInIdsRes) Reset() {
	*x = FindItemsInIdsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_item_itemPb_itemPb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindItemsInIdsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindItemsInIdsRes) ProtoMessage() {}

func (x *FindItemsInIdsRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_item_itemPb_itemPb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindItemsInIdsRes.ProtoReflect.Descriptor instead.
func (*FindItemsInIdsRes) Descriptor() ([]byte, []int) {
	return file_modules_item_itemPb_itemPb_proto_rawDescGZIP(), []int{1}
}

func (x *FindItemsInIdsRes) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price    float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl string  `protobuf:"bytes,4,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Damage   int32   `protobuf:"varint,5,opt,name=damage,proto3" json:"damage,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_item_itemPb_itemPb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_modules_item_itemPb_itemPb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_modules_item_itemPb_itemPb_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Item) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

var File_modules_item_itemPb_itemPb_proto protoreflect.FileDescriptor

var file_modules_item_itemPb_itemPb_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x2f, 0x69,
	0x74, 0x65, 0x6d, 0x50, 0x62, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x50, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x25, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49,
	0x6e, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x30, 0x0a, 0x11, 0x46, 0x69, 0x6e,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x12, 0x1b,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x76, 0x0a, 0x04, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x61, 0x6d,
	0x61, 0x67, 0x65, 0x32, 0x4b, 0x0a, 0x0f, 0x49, 0x74, 0x65, 0x6d, 0x47, 0x72, 0x70, 0x63, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x49, 0x6e, 0x49, 0x64, 0x73, 0x12, 0x12, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73,
	0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52,
	0x61, 0x79, 0x61, 0x74, 0x6f, 0x31, 0x35, 0x39, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2d, 0x73,
	0x65, 0x6b, 0x61, 0x69, 0x2d, 0x73, 0x68, 0x6f, 0x70, 0x2d, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69,
	0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_item_itemPb_itemPb_proto_rawDescOnce sync.Once
	file_modules_item_itemPb_itemPb_proto_rawDescData = file_modules_item_itemPb_itemPb_proto_rawDesc
)

func file_modules_item_itemPb_itemPb_proto_rawDescGZIP() []byte {
	file_modules_item_itemPb_itemPb_proto_rawDescOnce.Do(func() {
		file_modules_item_itemPb_itemPb_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_item_itemPb_itemPb_proto_rawDescData)
	})
	return file_modules_item_itemPb_itemPb_proto_rawDescData
}

var file_modules_item_itemPb_itemPb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_modules_item_itemPb_itemPb_proto_goTypes = []interface{}{
	(*FindItemsInIdsReq)(nil), // 0: FindItemsInIdsReq
	(*FindItemsInIdsRes)(nil), // 1: FindItemsInIdsRes
	(*Item)(nil),              // 2: Item
}
var file_modules_item_itemPb_itemPb_proto_depIdxs = []int32{
	2, // 0: FindItemsInIdsRes.items:type_name -> Item
	0, // 1: ItemGrpcService.FindItemsInIds:input_type -> FindItemsInIdsReq
	1, // 2: ItemGrpcService.FindItemsInIds:output_type -> FindItemsInIdsRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_modules_item_itemPb_itemPb_proto_init() }
func file_modules_item_itemPb_itemPb_proto_init() {
	if File_modules_item_itemPb_itemPb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_item_itemPb_itemPb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindItemsInIdsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_item_itemPb_itemPb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindItemsInIdsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_item_itemPb_itemPb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_item_itemPb_itemPb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_item_itemPb_itemPb_proto_goTypes,
		DependencyIndexes: file_modules_item_itemPb_itemPb_proto_depIdxs,
		MessageInfos:      file_modules_item_itemPb_itemPb_proto_msgTypes,
	}.Build()
	File_modules_item_itemPb_itemPb_proto = out.File
	file_modules_item_itemPb_itemPb_proto_rawDesc = nil
	file_modules_item_itemPb_itemPb_proto_goTypes = nil
	file_modules_item_itemPb_itemPb_proto_depIdxs = nil
}
